### ISSUE TITLE
Potential dropouts due to VU meteres

### ISSUE THREAD

**Issue by aebrouse** [AScustomWorks/AS#15] opened 2018-04-01 02:39 UTC
Hey Alfredo,  
  YEs , the problems I had had been having with Rack  seems to stem from your VU meters.. Attached are both the patch that gave issues and the same patch without your meters.    

- System stats , Asus PN5-Y motherboard
Intel Core two quad Q9300 running at 2.75 GHz 
8 GB DDR2 ram 
NVidia GeForce 550 Ti ( adding this because I can also use GPU for HDMI audio) 
Windows 7 home Premium ..Up to date 

[06trialrack.zip](https://github.com/AScustomWorks/AS/files/1866067/06trialrack.zip)

I am sure you followed my posts in group.. oh and your tiny OSC's .. They flicker randomly not in any relation to frequency generated.

**Comment by AScustomWorks** [comment] 2018-04-01 07:00
Is this patch making the audio glitches? Tried it (without Bidoo module, I can't install it yet) and everything else appeared to be working fine even when setting the block size to 64 so I can't reproduce the error.

Try making a new patch from zero (so you can discard patch weirdness), and narrowing it down to the least amount of modules needed to reproduce the glitches, using only AS modules would be even better for the sake of testing.

Also, maybe not that relevant as it seems to be working, but the VU meters are not meant to read -V, and the signal is not clamped, otherwise you couldn't monitor saturated signal levels. It may be worth checking that routing on your LFOs. If anything, the VU meters are only showing you the positive half of the signal.

**Comment by AScustomWorks** [comment] 2018-04-01 17:28
Now, on the code side this is all what's happening with the VU meters:
```
	//GET VALUES AND ROUTE SIGNALS TO OUTPUTS
	float signal_in_Left = inputs[INPUT_LEFT].value;
	float signal_in_Right = inputs[INPUT_RIGHT].value;
	outputs[OUT_LEFT].value = signal_in_Left;
	outputs[OUT_RIGHT].value = signal_in_Right;
	//VU METER BARS LIGHTS
	vuBar.dBInterval = 3;
	for (int i = 0; i < 15; i++){
		vuBar.setValue(signal_in_Left / 10.0f);
		lights[METER_LIGHT_LEFT + i].setBrightnessSmooth(vuBar.getBrightness(i));
		vuBar.setValue(signal_in_Right / 10.0f);
		lights[METER_LIGHT_RIGHT + i].setBrightnessSmooth(vuBar.getBrightness(i));
	}
```
Can't see how this code would make audio glitches compared to what any complex (vcos for example)module is doing internally. 

I could test your original patch now with Bidoo module too, everything still fine. I'll wait for a simpler patch with the error ;)

**Comment by aebrouse** [comment] 2018-04-02 04:44
Freddy, I can put together a simple patch to see if I can reproduce the error .. all I know is that I only get this problem with the vu meters running .. i'll get back to you soonest.    Yes , I figured the code would be uber-simple . worse-to-worst Ill just have to patch without your oh so pretty meters 😊


________________________________

**Comment by aebrouse** [comment] 2018-04-02 04:47
Um it seems that the error does not occur unless I have 2 or more vu meters running at same time I normally run 4 or 8 stereo meters...  at this moment I am running a nearly simple patch with just one stereo vu meter monitoring  output to interface and no problem.   I'll experiment some more to reproduce error.

________________________________

**Comment by AScustomWorks** [comment] 2018-04-03 19:00
closing this one, follow up [here](https://github.com/AScustomWorks/AS/issues/16)

**Closed by AScustomWorks** 2018-04-03 19:00 UTC
